### ISSUE TITLE
architect_Alvaro Froylan Pacheco Osoio

### ISSUE THREAD

**Issue by Alvaro2-0** [SistemasTecTlaxiaco/actividad-3-practica-architect-Alvaro2-0#1]
[DIAGRAMA DE CLASE-ARCHITECT-ALVARO FROYLAN PACH.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-architect-Alvaro2-0/files/12581120/DIAGRAMA.DE.CLASE-ARCHITECT-ALVARO.FROYLAN.PACH.pdf)

**Comment by Julissamigdalia** [comment]
Buen trabajo, faltó descripción de materia.
Calificación: 18/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado....
